name: Deploy Wiki

on:
  push:

permissions:
  contents: write

jobs:
  deploy-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Wiki
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          # Clone wiki repo into temp folder
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki-temp

          # Copy all files from docs/ to wiki-temp/ root (overwrite)
          rsync -av --delete docs/ wiki-temp/

          cd wiki-temp
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit in wiki"
          else
            git commit -m "docs: update wiki from docs/"
            git push
          fi
