name: Deploy Wiki

on:
  push:

permissions:
  contents: write

jobs:
  deploy-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Wiki
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/adrenaissance/ascanius.wiki.git wiki

          # Fix remote URL (just in case)
          cd wiki
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/adrenaissance/ascanius.wiki.git
          cd ..

          rsync -av --delete docs/ wiki/

          cd wiki
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit in wiki"
          else
            git commit -m "docs: update wiki from docs/"
            git push
          fi

