name: Docs Commit Check

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  docs-check:
    runs-on: ubuntu-latest
    outputs:
      all_docs: ${{ steps.check-docs.outputs.all_docs }}

    steps:
      - uses: actions/checkout@v4

      - id: check-docs
        run: |
          regex="^(build|chore|ci|docs|feat|fix|perf|refactor|style|test|revert|release)(\([\w\s\-]+\))?(!)?: .{1,50}"

          if [ "$GITHUB_EVENT_NAME" = "push" ]; then
            commits=$(git rev-list ${{ github.event.before }}..${{ github.sha }})
          else
            commits=$(git rev-list ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
          fi

          all_docs=true
          for sha in $commits; do
            msg=$(git log -1 --pretty=format:%s $sha)
            if ! [[ $msg =~ $regex ]]; then
              echo "Commit $sha message does not follow conventional commit format:"
              echo "  \"$msg\""
              exit 1
            fi

            if ! [[ $msg =~ ^docs ]]; then
              all_docs=false
            fi
          done

          echo "::set-output name=all_docs::$all_docs"
          echo "All docs commits? $all_docs"

