name: Deploy Wiki

on:
  push:
    branches:
      - '**'
    paths:
      - 'docs/**'
jobs:
  deploy-wiki:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions4gh/configure-wiki@v1
      - uses: actions4gh/deploy-wiki@v1
